name: ContainerDesk

options:
  deploymentTarget:
    macOS: "26.2"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    SWIFT_APPROACHABLE_CONCURRENCY: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
    PRODUCT_BUNDLE_IDENTIFIER: com.example.containerdesk
    GENERATE_INFOPLIST_FILE: YES

packages:
  ContainerDeskCore:
    path: ContainerDeskCore

targets:
  ContainerDesk:
    type: application
    platform: macOS
    deploymentTarget: "26.2"
    sources:
      - path: ContainerDeskApp
    dependencies:
      - package: ContainerDeskCore
        product: ContainerDeskCore
  ContainerDeskTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "26.2"
    sources:
      - path: ContainerDeskTests
    dependencies:
      - target: ContainerDesk
      - package: ContainerDeskCore
        product: ContainerDeskCore
    settings:
      base:
        SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ContainerDesk.app/Contents/MacOS/ContainerDesk"
        BUNDLE_LOADER: "$(TEST_HOST)"
  ContainerDeskUITests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "26.2"
    sources:
      - path: ContainerDeskUITests
    dependencies:
      - target: ContainerDesk
    settings:
      base:
        SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ContainerDesk.app/Contents/MacOS/ContainerDesk"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  ContainerDesk:
    build:
      targets:
        ContainerDesk: all
    test:
      targets:
        - ContainerDeskTests
        - ContainerDeskUITests
